/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthForgotOtpRouteImport } from './routes/_auth.forgot-otp'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicCartRouteImport } from './routes/_public.cart'
import { Route as PublicCheckoutRouteImport } from './routes/_public.checkout'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicProjectsRouteImport } from './routes/_public.projects'
import { Route as PublicServicesRouteImport } from './routes/_public.services'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityLogRouteImport } from './routes/admin.activity-log'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersUsersRouteImport } from './routes/admin.orders-users'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPosSalesRouteImport } from './routes/admin.pos-sales'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStockMovementsRouteImport } from './routes/admin.stock-movements'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardAddressesRouteImport } from './routes/dashboard.addresses'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSupportRouteImport } from './routes/dashboard.support'
import { Route as PublicInvoiceOrderNumberRouteImport } from './routes/_public.invoice.$orderNumber'
import { Route as PublicPaymentFailedRouteImport } from './routes/_public.payment.failed'
import { Route as PublicPaymentProcessingRouteImport } from './routes/_public.payment.processing'
import { Route as PublicPaymentSuccessRouteImport } from './routes/_public.payment.success'
import { Route as PublicShopIndexRouteImport } from './routes/_public.shop.index'
import { Route as PublicShopSlugRouteImport } from './routes/_public.shop.$slug'
import { Route as DashboardOrdersIndexRouteImport } from './routes/dashboard.orders.index'
import { Route as DashboardOrdersIdRouteImport } from './routes/dashboard.orders.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotOtpRoute = AuthForgotOtpRouteImport.update({
  id: '/forgot-otp',
  path: '/forgot-otp',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCartRoute = PublicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsRoute = PublicProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogRoute = AdminActivityLogRouteImport.update({
  id: '/activity-log',
  path: '/activity-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersUsersRoute = AdminOrdersUsersRouteImport.update({
  id: '/orders-users',
  path: '/orders-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosSalesRoute = AdminPosSalesRouteImport.update({
  id: '/pos-sales',
  path: '/pos-sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStockMovementsRoute = AdminStockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAddressesRoute = DashboardAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicInvoiceOrderNumberRoute =
  PublicInvoiceOrderNumberRouteImport.update({
    id: '/invoice/$orderNumber',
    path: '/invoice/$orderNumber',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPaymentFailedRoute = PublicPaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPaymentProcessingRoute = PublicPaymentProcessingRouteImport.update({
  id: '/payment/processing',
  path: '/payment/processing',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPaymentSuccessRoute = PublicPaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShopIndexRoute = PublicShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShopSlugRoute = PublicShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardOrdersIndexRoute = DashboardOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersIdRoute = DashboardOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-otp': typeof AuthForgotOtpRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/cart': typeof PublicCartRoute
  '/checkout': typeof PublicCheckoutRoute
  '/contact': typeof PublicContactRoute
  '/privacy': typeof PublicPrivacyRoute
  '/projects': typeof PublicProjectsRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders-users': typeof AdminOrdersUsersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pos-sales': typeof AdminPosSalesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock-movements': typeof AdminStockMovementsRoute
  '/admin/support': typeof AdminSupportRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/invoice/$orderNumber': typeof PublicInvoiceOrderNumberRoute
  '/payment/failed': typeof PublicPaymentFailedRoute
  '/payment/processing': typeof PublicPaymentProcessingRoute
  '/payment/success': typeof PublicPaymentSuccessRoute
  '/shop/$slug': typeof PublicShopSlugRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/shop/': typeof PublicShopIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forgot-otp': typeof AuthForgotOtpRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof PublicAboutRoute
  '/cart': typeof PublicCartRoute
  '/checkout': typeof PublicCheckoutRoute
  '/contact': typeof PublicContactRoute
  '/privacy': typeof PublicPrivacyRoute
  '/projects': typeof PublicProjectsRoute
  '/services': typeof PublicServicesRoute
  '/terms': typeof PublicTermsRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders-users': typeof AdminOrdersUsersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pos-sales': typeof AdminPosSalesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock-movements': typeof AdminStockMovementsRoute
  '/admin/support': typeof AdminSupportRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/invoice/$orderNumber': typeof PublicInvoiceOrderNumberRoute
  '/payment/failed': typeof PublicPaymentFailedRoute
  '/payment/processing': typeof PublicPaymentProcessingRoute
  '/payment/success': typeof PublicPaymentSuccessRoute
  '/shop/$slug': typeof PublicShopSlugRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/shop': typeof PublicShopIndexRoute
  '/dashboard/orders': typeof DashboardOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_auth/forgot-otp': typeof AuthForgotOtpRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/cart': typeof PublicCartRoute
  '/_public/checkout': typeof PublicCheckoutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/projects': typeof PublicProjectsRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/terms': typeof PublicTermsRoute
  '/admin/activity-log': typeof AdminActivityLogRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders-users': typeof AdminOrdersUsersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pos-sales': typeof AdminPosSalesRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stock-movements': typeof AdminStockMovementsRoute
  '/admin/support': typeof AdminSupportRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/addresses': typeof DashboardAddressesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/support': typeof DashboardSupportRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/invoice/$orderNumber': typeof PublicInvoiceOrderNumberRoute
  '/_public/payment/failed': typeof PublicPaymentFailedRoute
  '/_public/payment/processing': typeof PublicPaymentProcessingRoute
  '/_public/payment/success': typeof PublicPaymentSuccessRoute
  '/_public/shop/$slug': typeof PublicShopSlugRoute
  '/dashboard/orders/$id': typeof DashboardOrdersIdRoute
  '/_public/shop/': typeof PublicShopIndexRoute
  '/dashboard/orders/': typeof DashboardOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-otp'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/admin/activity-log'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders-users'
    | '/admin/payments'
    | '/admin/pos-sales'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stock-movements'
    | '/admin/support'
    | '/dashboard/account'
    | '/dashboard/addresses'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/admin/'
    | '/dashboard/'
    | '/invoice/$orderNumber'
    | '/payment/failed'
    | '/payment/processing'
    | '/payment/success'
    | '/shop/$slug'
    | '/dashboard/orders/$id'
    | '/shop/'
    | '/dashboard/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-otp'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/privacy'
    | '/projects'
    | '/services'
    | '/terms'
    | '/admin/activity-log'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders-users'
    | '/admin/payments'
    | '/admin/pos-sales'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stock-movements'
    | '/admin/support'
    | '/dashboard/account'
    | '/dashboard/addresses'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/admin'
    | '/dashboard'
    | '/invoice/$orderNumber'
    | '/payment/failed'
    | '/payment/processing'
    | '/payment/success'
    | '/shop/$slug'
    | '/dashboard/orders/$id'
    | '/shop'
    | '/dashboard/orders'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/admin'
    | '/dashboard'
    | '/_auth/forgot-otp'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_public/about'
    | '/_public/cart'
    | '/_public/checkout'
    | '/_public/contact'
    | '/_public/privacy'
    | '/_public/projects'
    | '/_public/services'
    | '/_public/terms'
    | '/admin/activity-log'
    | '/admin/customers'
    | '/admin/notifications'
    | '/admin/orders-users'
    | '/admin/payments'
    | '/admin/pos-sales'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/stock-movements'
    | '/admin/support'
    | '/dashboard/account'
    | '/dashboard/addresses'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/support'
    | '/_public/'
    | '/admin/'
    | '/dashboard/'
    | '/_public/invoice/$orderNumber'
    | '/_public/payment/failed'
    | '/_public/payment/processing'
    | '/_public/payment/success'
    | '/_public/shop/$slug'
    | '/dashboard/orders/$id'
    | '/_public/shop/'
    | '/dashboard/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-otp': {
      id: '/_auth/forgot-otp'
      path: '/forgot-otp'
      fullPath: '/forgot-otp'
      preLoaderRoute: typeof AuthForgotOtpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/cart': {
      id: '/_public/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicCartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects': {
      id: '/_public/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof PublicProjectsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity-log': {
      id: '/admin/activity-log'
      path: '/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AdminActivityLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders-users': {
      id: '/admin/orders-users'
      path: '/orders-users'
      fullPath: '/admin/orders-users'
      preLoaderRoute: typeof AdminOrdersUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos-sales': {
      id: '/admin/pos-sales'
      path: '/pos-sales'
      fullPath: '/admin/pos-sales'
      preLoaderRoute: typeof AdminPosSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stock-movements': {
      id: '/admin/stock-movements'
      path: '/stock-movements'
      fullPath: '/admin/stock-movements'
      preLoaderRoute: typeof AdminStockMovementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/addresses': {
      id: '/dashboard/addresses'
      path: '/addresses'
      fullPath: '/dashboard/addresses'
      preLoaderRoute: typeof DashboardAddressesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support': {
      id: '/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/invoice/$orderNumber': {
      id: '/_public/invoice/$orderNumber'
      path: '/invoice/$orderNumber'
      fullPath: '/invoice/$orderNumber'
      preLoaderRoute: typeof PublicInvoiceOrderNumberRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/payment/failed': {
      id: '/_public/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PublicPaymentFailedRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/payment/processing': {
      id: '/_public/payment/processing'
      path: '/payment/processing'
      fullPath: '/payment/processing'
      preLoaderRoute: typeof PublicPaymentProcessingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/payment/success': {
      id: '/_public/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PublicPaymentSuccessRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shop/': {
      id: '/_public/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof PublicShopIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shop/$slug': {
      id: '/_public/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof PublicShopSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/orders/': {
      id: '/dashboard/orders/'
      path: '/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof DashboardOrdersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders/$id': {
      id: '/dashboard/orders/$id'
      path: '/orders/$id'
      fullPath: '/dashboard/orders/$id'
      preLoaderRoute: typeof DashboardOrdersIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotOtpRoute: typeof AuthForgotOtpRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotOtpRoute: AuthForgotOtpRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCartRoute: typeof PublicCartRoute
  PublicCheckoutRoute: typeof PublicCheckoutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicProjectsRoute: typeof PublicProjectsRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicInvoiceOrderNumberRoute: typeof PublicInvoiceOrderNumberRoute
  PublicPaymentFailedRoute: typeof PublicPaymentFailedRoute
  PublicPaymentProcessingRoute: typeof PublicPaymentProcessingRoute
  PublicPaymentSuccessRoute: typeof PublicPaymentSuccessRoute
  PublicShopSlugRoute: typeof PublicShopSlugRoute
  PublicShopIndexRoute: typeof PublicShopIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCartRoute: PublicCartRoute,
  PublicCheckoutRoute: PublicCheckoutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicProjectsRoute: PublicProjectsRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicInvoiceOrderNumberRoute: PublicInvoiceOrderNumberRoute,
  PublicPaymentFailedRoute: PublicPaymentFailedRoute,
  PublicPaymentProcessingRoute: PublicPaymentProcessingRoute,
  PublicPaymentSuccessRoute: PublicPaymentSuccessRoute,
  PublicShopSlugRoute: PublicShopSlugRoute,
  PublicShopIndexRoute: PublicShopIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminActivityLogRoute: typeof AdminActivityLogRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersUsersRoute: typeof AdminOrdersUsersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPosSalesRoute: typeof AdminPosSalesRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStockMovementsRoute: typeof AdminStockMovementsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityLogRoute: AdminActivityLogRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersUsersRoute: AdminOrdersUsersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPosSalesRoute: AdminPosSalesRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStockMovementsRoute: AdminStockMovementsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAddressesRoute: typeof DashboardAddressesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrdersIdRoute: typeof DashboardOrdersIdRoute
  DashboardOrdersIndexRoute: typeof DashboardOrdersIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAddressesRoute: DashboardAddressesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrdersIdRoute: DashboardOrdersIdRoute,
  DashboardOrdersIndexRoute: DashboardOrdersIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
